version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
#      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443

  jackstand:
    image: golang:latest
    volumes:
      - .:/go/src/jackstand
    working_dir: /go/src/jackstand
    environment:
      - PORT=${PORT:-4000}
      - FIREBASE_API_KEY=${FIREBASE_API_KEY:-key}
      - S3_BUCKET=${S3_BUCKET:-jackstand}
    command: go clean -modcache && go mod tidy && go mod vendor && go run main.go serve

    # ports:
    #   - 4000:4000







